### ISSUE TITLE
I want to download 'djpegnet.pth' ver. pytorch

### ISSUE THREAD

**Issue by sdc0319** [plok5308/DJPEG-torch#1]
I tried to download your djpegnet.pth, but download shell didn't work.
if you can send to me your pth, to my e-mail (tlsejrcjf@naver.com)
it will be a very good help to me.
Thank you!

**Comment by plok5308** [comment]
Hi, 
Can you download using below link?
https://drive.google.com/file/d/1OYAqDGovzPn8qTL1zEesbheByt5DUi7o/view?usp=sharing
If you can not download, please leave message.
Thank you.

**Comment by sdc0319** [comment]
Thanks your kind! 😊
